#!/usr/bin/python

import glob
import os
import os.path as osp
from subprocess import call

for file in glob.glob("*.po"):
    lang = file[:-3]
    try:
        os.makedirs(osp.join(lang, 'LC_MESSAGES'), 0755)
    except OSError:
        pass
    call(['msgfmt', '-o', osp.join(lang, 'LC_MESSAGES', 'LBRC.mo'), file])
