#!/usr/bin/python

import pygtk
pygtk.require("2.0")
import dbus, dbus.glib
import gtk
import gobject
import time
import sys
from LBRC import get_binfile, dinterface
from LBRC_gtk_gui.applet import Applet
from LBRC.l10n import _

count = 0
ok = 0
while count < 10:
    try:
        lbrc_interface = dinterface(dbus.SessionBus(), 'custom.LBRC', '/custom/LBRC', 'custom.LBRC')
        lbrc_interface.get_profiles()
        ok = 1
        break
    except dbus.DBusException:
        if count == 0:
            # We got an dbus exception => our service is not running, so
            # try to invoke it (if dbus activation would have worked, we
            # the get_profiles call would have blocked till it was started)
            # But we try the invokation only once!
            gobject.spawn_async([get_binfile("LBRCdbus.py")], 
                                flags= gobject.SPAWN_STDOUT_TO_DEV_NULL | 
                                       gobject.SPAWN_STDERR_TO_DEV_NULL )

        count += 1
        time.sleep(0.5)
if not ok:
    print _("Could not connect to DBUS component of LBRC")
    sys.exit(1)
else:
    lbrc = Applet(lbrc_interface)
    try:
        gtk.main()
    except KeyboardInterrupt:
        lbrc.quit()
        gtk.mainquit()
