#!/usr/bin/python

import pygtk
pygtk.require("2.0")
import gtk
import gobject
import dbus
import dbus.glib
import time
import sys
import logging
from LBRC import dinterface
from LBRC.path import path
from LBRC_gtk_gui.config import ConfigWindow
from LBRC.l10n import _

formatter = logging.Formatter('%(asctime)s %(name)-8s %(levelname)-8s %(message)s')
console = logging.StreamHandler()
logging.getLogger().addHandler(console)
console.setLevel(logging.WARN)
console.setFormatter(formatter)

if '--debug' in sys.argv:
    console.setLevel(logging.DEBUG)

logger = logging.getLogger('Applet')

if 'de.berlios.lbrc' in dbus.SessionBus().list_names():
    lbrc_core = dinterface( dbus.SessionBus(), 
                            'de.berlios.lbrc', 
                            '/core', 
                            'de.berlios.lbrc')
else:
    lbrc_core = None

if "--only-reload" in sys.argv and lbrc_core:
	lbrc_core.reload_config()
	sys.exit(0)

def config_close_handler(config_dialog, changed):
    if changed and lbrc_core:
        # If the core was running - inform it about the config change
        lbrc_core.reload_config()
    gtk.main_quit()

config_dialog = ConfigWindow()
config_dialog.connect("close", config_close_handler)
gtk.main()