#!/usr/bin/python

from subprocess import call

glade_files = ["../LBRC_gtk_gui/config.glade"]
python_files = ["../LBRC-applet",
                "../LBRC_gtk_gui/applet.py",
                "../LBRC_gtk_gui/BlueZControl.py",
                "../LBRC_gtk_gui/config.py"]

for glade in glade_files:
    call(["intltool-extract", "--type=gettext/glade", glade])

extract_call= ["xgettext",  
               "--language=Python", 
               "--keyword=_",  
               "--keyword=N_",  
               "--output=LBRC.pot"]
extract_call.extend(python_files)
extract_call.extend([ gl + ".h" for gl in glade_files ])

call(extract_call)
