#!/bin/bash
cd dbus_uinput_bridge
CC='gcc'
BINDINGTOOL='dbus-binding-tool'
BASENAME="uinputbridge"
CFLAGS=`pkg-config --cflags dbus-glib-1`
LIBS=`pkg-config --libs dbus-glib-1`
$BINDINGTOOL --mode=glib-server --output=$BASENAME-glue.h \
             --prefix=uinputbridge $BASENAME.xml
$CC $CFLAGS $LIBS -o ../$BASENAME $BASENAME.c
